DirectoryIndex index.html
DocumentRoot /app
<Directory /app>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<FilesMatch "\.(html|css|js)$">
    Require all granted
</FilesMatch>